name: Trigger Deployment

on:
  push:
    branches:
      - master

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ddhanawade/fleet-manager-deployment
          event-type: deploy